/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.1
 * Generated at: 2022-11-18 09:22:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import models.User;
import models.User;

public final class userprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/navbar.jsp", Long.valueOf(1666584104000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("models.User");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!DOCTYPE html>\r\n");
      out.write("  <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\">\r\n");
      out.write("    <!--External CSS File-->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <!-- Awesome Font -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("\r\n");
      out.write("    <!--Bootstrap 4-->\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"bootstrap/css/bootstrap.min.css\" type=\"text/css\"> CSS\r\n");
      out.write("    <script src=\"bootstrap/js/bootstrap.min.js\"></script> -->\r\n");
      out.write("    <!-- <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("      integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.slim.min.js\"\r\n");
      out.write("      integrity=\"sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js\"\r\n");
      out.write("      integrity=\"sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js\"\r\n");
      out.write("      integrity=\"sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script> -->\r\n");
      out.write("\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("      crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("      <script src=\"https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone-min.js\"></script>\r\n");
      out.write("      <link href=\"https://unpkg.com/dropzone@6.0.0-beta.1/dist/dropzone.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      .header {\r\n");
      out.write("\r\n");
      out.write("        min-height: 10vh;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        background-image: linear-gradient(rgba(4, 9, 30, 0.7), rgba(4, 9, 30, 0.7)), url(images/pgimage.jpg);\r\n");
      out.write("        background-position: center;\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("        position: relative;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /* jjjjjjjjjjjjjjj */\r\n");
      out.write("\r\n");
      out.write("      #drop_img {\r\n");
      out.write("            width: 250px;\r\n");
      out.write("            /* border: 5px dashed #111; */\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            margin: 5px auto;\r\n");
      out.write("            background: url(images/use.png);\r\n");
      out.write("            background-size:250px;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-repeat:no-repeat;\r\n");
      out.write("            \r\n");
      out.write("            color: #555;\r\n");
      out.write("            font-family: verdana;\r\n");
      out.write("            font-size: 26px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #drop_img .dz-preview {\r\n");
      out.write("\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            border: 3px solid red;\r\n");
      out.write("            position:relative;\r\n");
      out.write("            right:41px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        .dropzone .dz-preview .dz-image {\r\n");
      out.write("\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            width:250px;\r\n");
      out.write("            height:250px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* .dropzone .dz-preview .dz-success-mark,\r\n");
      out.write("        .dropzone .dz-preview .dz-error-mark {\r\n");
      out.write("\r\n");
      out.write("        } */\r\n");
      out.write("\r\n");
      out.write("        .dropzone .dz-message .dz-button {\r\n");
      out.write("\r\n");
      out.write("            width: 120px;\r\n");
      out.write("            height: 120px;\r\n");
      out.write("            /* border: 3px solid black; */\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .dropzone .dz-preview .dz-image img {\r\n");
      out.write("\r\n");
      out.write("             width:250px;\r\n");
      out.write("             position:relative;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("   #img {\r\n");
      out.write("\r\n");
      out.write("    width:170px;    \r\n");
      out.write("    height:140px;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    \r\n");
      out.write("   }\r\n");
      out.write("  \r\n");
      out.write("     #msg {\r\n");
      out.write("\r\n");
      out.write("      display: none;\r\n");
      out.write("      \r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #update {\r\n");
      out.write("\r\n");
      out.write("      display: none;\r\n");
      out.write("      color: red;\r\n");
      out.write("      position:relative;\r\n");
      out.write("      top:80px;\r\n");
      out.write("      left:175px;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     #save_btn {\r\n");
      out.write("\t\t\tcolor: #ffffff;\r\n");
      out.write("\t\t\tbackground-color: #a28553;\r\n");
      out.write("\t\t\tfont-size: 19px;\r\n");
      out.write("\t\t\tborder: 1px solid #2d63c8;\r\n");
      out.write("\t\t\tborder-radius: 6px;\r\n");
      out.write("\t\t\tpadding: 15px 20px;\r\n");
      out.write("\t\t\tletter-spacing: 1px;\r\n");
      out.write("\t\t\tcursor: pointer;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      left: 150px;\r\n");
      out.write("      top:150px;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#save_btn:hover {\r\n");
      out.write("\t\t\tcolor: #2d63c8;\r\n");
      out.write("\t\t\tbackground-color: #ffffff;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("    .bg-custom {\r\n");
      out.write("\r\n");
      out.write("      background-color: rgb(228, 221, 184);\r\n");
      out.write("      height:450px;\r\n");
      out.write("      width:3000px;\r\n");
      out.write("      border-radius: 15px;\r\n");
      out.write("    }\r\n");
      out.write("        \r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body style=\"background-color: rgb(228, 221, 184);\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <section class=\"header\">\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<nav>\r\n");
      out.write("    <a href=\"indes.html\" style=\"text-decoration:none; color:white; \">\r\n");
      out.write("        <h1 style=\"display: inline-block; font-size: 50px;\">LOGO</h1>\r\n");
      out.write("    </a>\r\n");
      out.write("\r\n");
      out.write("  ");
  User us = (User)session.getAttribute("user"); 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"nav-links\" id=\"navLinks\">\r\n");
      out.write("        <i class=\"fa fa-times\" onclick=\"hideMenu()\"></i>\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li><a href=\"#\">HOME</a></li>\r\n");
      out.write("            <li><a href=\"\">PG</a></li>\r\n");
      out.write("            <li><a href=\"\">ABOUT</a></li>\r\n");
      out.write("\r\n");
      out.write(" ");
 if(us!=null) { 
      out.write("\r\n");
      out.write("         <div class=\"w3-dropdown-hover\">\r\n");
      out.write("            <button class=\"w3-button w3-block\" style=\"color:white\">MY ACCOUNT</button>\r\n");
      out.write("            <div class=\"w3-dropdown-content w3-bar-block w3-border\">\r\n");
      out.write("              <a href=\"userprofile.jsp\" class=\"w3-bar-item w3-button\">My Profile</a>\r\n");
      out.write("              <a href=\"#\" class=\"w3-bar-item w3-button\">My Booking</a>\r\n");
      out.write("              <a href=\"#\" class=\"w3-bar-item w3-button\">Change Password</a>\r\n");
      out.write("              <a href=\"#\" class=\"w3-bar-item w3-button\">Logout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("      ");
 } else { 
      out.write("\r\n");
      out.write("            <li><a href=\"ownerlogin.do\">OWNER</a></li>\r\n");
      out.write("\r\n");
      out.write("            <li><a href=\"userlogin.do\">LOGIN/REGISTER</a></li>\r\n");
      out.write("         ");
 } 
      out.write("   \r\n");
      out.write("            <li><a href=\"\">CONTACT</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <i class=\"fa fa-bars\" onclick=\"showMenu()\"></i>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("<h1 class=\"nm\">Welcome Back: ");
      out.print( us.getName() );
      out.write("</h1>\r\n");
      out.write("\r\n");
 if(us.getPincode() == null) { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"msg\">\r\n");
      out.write("  Updation Failed... Try again later...\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"update\">\r\n");
      out.write("  Successfully Updated\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container  bg-custom\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <div class=\"profile-links\">\r\n");
      out.write("\r\n");
      out.write("            <!-- <img src=\"images/use.png\" alt=\"\"> -->\r\n");
      out.write("            <div id=\"drop_img\" class=\"dropzone\">\r\n");
      out.write("              <div class=\"dz-message\" data-dz-message><button class=\"dz-button\" type=\"button\">Drop</button></div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"text-align: center;\">\r\n");
      out.write("            <input type=\"button\" value=\"Upload\" id=\"btn\">\r\n");
      out.write("        </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <div class=\"mt-custum\">\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  Address\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                  <input type=\"text\" id=\"address\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  Gender\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                <input type=\"text\" id=\"gender\" placeholder=\"M / F\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  Pincode\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                  <input type=\"text\" id=\"pincode\" >\r\n");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"details\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-8\">\r\n");
      out.write("                  City\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-4\">\r\n");
      out.write("                  <input type=\"text\" id=\"city\" >\r\n");
      out.write("\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("         <input type=\"button\" id=\"save_btn\" value=\"update\"></input>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write(" ");
  } else { 
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container bg-custom\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-6\">\r\n");
      out.write("        <div class=\"profile-links\">\r\n");
      out.write("\r\n");
      out.write("          <img src=\"show_pic.do\" alt=\"\" id=\"img\">\r\n");
      out.write("          <!-- <div id=\"drop_img\" class=\"dropzone\">\r\n");
      out.write("            <div class=\"dz-message\" data-dz-message><button class=\"dz-button\" type=\"button\">Drop</button></div>\r\n");
      out.write("        </div> -->\r\n");
      out.write("        <!-- <div style=\"text-align: center;\">\r\n");
      out.write("          <input type=\"button\" value=\"Upload\" id=\"btn\">\r\n");
      out.write("      </div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-6\">\r\n");
      out.write("        <div class=\"mt-custum\">\r\n");
      out.write("          <div class=\"details\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-8\">\r\n");
      out.write("                Address\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-4\">\r\n");
      out.write("               ");
      out.print( us.getAddress() );
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"details\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-8\">\r\n");
      out.write("                Gender\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-4\">\r\n");
      out.write("              ");
      out.print( us.getGender() );
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"details\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-8\">\r\n");
      out.write("                Pincode\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-4\">\r\n");
      out.write("                ");
      out.print( us.getPincode() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"details\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-8\">\r\n");
      out.write("                City\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-4\">\r\n");
      out.write("                ");
      out.print( us.getCity() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("       <!-- <input type=\"button\" id=\"save_btn\" value=\"update\"></input> -->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");
 } 
      out.write("\r\n");
      out.write("<!-- <script src=\"JS/script.js\"></script> -->\r\n");
      out.write("    <script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("const btn = document.querySelector('#btn');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("let dropImg = new Dropzone('#drop_img', {\r\n");
      out.write("    url: 'upload.do?uemail=");
      out.print( us.getEmail() );
      out.write("',\r\n");
      out.write("    maxFiles: 5,\r\n");
      out.write("    acceptedFiles: 'image/png,.jpg,.gif',\r\n");
      out.write("    autoProcessQueue: false,\r\n");
      out.write("    createImageThumbnails: true,\r\n");
      out.write("    thumbnailWidth: 200,\r\n");
      out.write("    thumbnailHeight: 200,\r\n");
      out.write("    // addRemoveLinks: true\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("btn.addEventListener('click', () => {\r\n");
      out.write("    dropImg.processQueue();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("const address = document.querySelector(\"#address\");\r\n");
      out.write("const gender = document.querySelector(\"#gender\");\r\n");
      out.write("const pincode = document.querySelector(\"#pincode\");\r\n");
      out.write("const city = document.querySelector(\"#city\");\r\n");
      out.write("\r\n");
      out.write("const save_btn = document.querySelector('#save_btn');\r\n");
      out.write("\r\n");
      out.write("let save_req = null;\r\n");
      out.write("save_btn.addEventListener('click', () => {\r\n");
      out.write("\r\n");
      out.write("  console.log(\"om\");\r\n");
      out.write("    const obj = {address: address.value, gender: gender.value, pincode: pincode.value, city: city.value};          \r\n");
      out.write("    var str = JSON.stringify(obj);\r\n");
      out.write("\r\n");
      out.write("    save_req = new XMLHttpRequest();\r\n");
      out.write("    \r\n");
      out.write("    save_req.open('GET', 'save.do?user_data='+encodeURIComponent(str), true);\r\n");
      out.write("    save_req.setRequestHeader('content-type', 'application/json');\r\n");
      out.write("    \r\n");
      out.write("    save_req.addEventListener('readystatechange', () => {\r\n");
      out.write("        if(save_req.readyState == 4 && save_req.status == 200) {\r\n");
      out.write("            if(save_req.responseText == 'yes') {\r\n");
      out.write("                document.querySelector(\"#update\").style.display = 'block';\r\n");
      out.write("            } else {\r\n");
      out.write("                document.querySelector('#msg').style.display = 'block';\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    save_req.send();\r\n");
      out.write("});\r\n");
      out.write("// console.log(email.value);\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("  </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
